### ISSUE TITLE
Exception has occurred. FormatException (FormatException: Unexpected character (at character 1) Country not found ^ )

### ISSUE THREAD

**Issue by cheikhounagueye** [madhavtripathi05/COVID_19_TRACKER#1]
Hello, 
I got this problem when i run the app.
![image](https://user-images.githubusercontent.com/20979143/77315623-c5403080-6cff-11ea-97d8-1368280d9168.png)

Please help me

**Comment by madhavtripathi05** [comment]
it's because your country is not on the list provided by API. for more you can file an Issue 
 here: https://github.com/NovelCOVID/API/issues

**Comment by madhavtripathi05** [comment]
I've to normalize the name of your Country will do soon!

**Comment by madhavtripathi05** [comment]
Fixed bruh, Thanks for reporting!
![ss](https://user-images.githubusercontent.com/22491498/77347506-f7807b00-6d5d-11ea-83c6-4badd9e56be1.png)
